#
# Copyright (c) 2001-2016 Primeton Technologies, Ltd.
# All rights reserved.
#
# author: ZhongWen Li (mailto:lizw@primeton.com)
#

#
# Note: Copy Dockerfile to WebRoot directory, maven project (webapp directory)
# tomcat7:2.0.0 TengLong custom version
#
FROM euler-registry.primeton.com/tomcat7:2.0.0

ADD . ${TOMCAT_HOME}/webapps/default/