#
# Copyright (c) 2001-2016 Primeton Technologies, Ltd.
# All rights reserved.
#
# author: ZhongWen Li (mailto:lizw@primeton.com)
#

FROM euler-registry.primeton.com/tomcat7:1.0.0

ADD ./resources/ROOT/ ${TOMCAT_HOME}/webapps/ROOT/